### ISSUE TITLE
[US] US 7 + Modifier mes informations de paiement

### ISSUE THREAD

**Issue by Xeltax** [KilianL55/E-Music#10]
## Données du User Story

• En tant que parent

•  Je peux modifier mes information de paiement

• Afin de payer l’inscription

## Team sur le projet

Team member : @LucaGiab714 

## Tâches à effectuer :

- [x] Création de l'affichage pour modifier les informations de payements
- [x] Mettre à jour en base de données les paiements

## Critères d'acceptation :
- [x] Je peux mettre à jour les informations de payement
- [ ] Mes données sont affichées de manière sécurisé
