### ISSUE TITLE
[US] US 9 + Consulter une inscription à un cours

### ISSUE THREAD

**Issue by Xeltax** [KilianL55/E-Music#13]
## Données du User Story

• En tant que parent

•  Je peux consulter une inscription à un cours

• Afin de savoir si je suis bien inscrit

## Team sur le projet

Team member : @Xeltax 

## Tâches à effectuer :

- [x] Voir dans le tableau de bord les cours
-  [x] Pouvoir se désinscrire
-  [x] Rediriger vers l'inscription de cours si aucun dans la liste

## Critères d'acceptation : 

- [x] Je peux m'inscrire et me désinscrire comme bon me semble
