### ISSUE TITLE
[US] US 10 + Retirer un membre de ma famille

### ISSUE THREAD

**Issue by Xeltax** [KilianL55/E-Music#15]
## Données du User Story

• En tant que parent

•  Je peux retirer un membre de ma famille

• Afin de ne plus avoir l’enfant sur le compte

## Team sur le projet

Team member : @KilianL55 

## Tâches à effectuer :

- [ ] Création de l'affichage des enfants
- [ ] Créer un d'un bouton pour désassigner un enfant d'un parent

## Critères d'acceptation :
- [ ] Je peux enlever un enfant de compte sans supprimer le compte de cette enfant
