### ISSUE TITLE
[US] US 11 + Modifier les informations de mes enfants

### ISSUE THREAD

**Issue by KilianL55** [KilianL55/E-Music#16]
## Données du User Story

• En tant que parent

•  Je peux modifier les informations de mon enfant

• Afin de mettre à jours les informations

## Team sur le projet

Team member : @KilianL55 

## Tâches à effectuer :

- [x] Création de l'affichage pour modifier les enfants
- [x] Mettre à jour en base de données l'enfant

## Critères d'acceptation :
- [x] Je peux mettre à jour les informations de mon enfant avec facilité
