### ISSUE TITLE
[US] US 2 + Ajouter son enfant

### ISSUE THREAD

**Issue by Xeltax** [KilianL55/E-Music#3]
# Modèle de création d'User Story

<h3>Données du User Story</h3>

• En tant que parent

•  Je peux créer un compte pour mon enfants

• Afin qu’il accède à ses cours

## Team sur le projet

Team member : @KilianL55 

## Tâches à effectuer :

- [x] Création formulaire
- [x] Enregistrement des données
- [x] Persistance des données

## Critères d'acceptation :

- [x] En tant que parent je peux créer un compte pour mon enfant
- [x] En tant que enfant je peux me connecter à l'application
- [x] En tant que enfant je peux voir les cours aux quels je suis inscrit
