### ISSUE TITLE
[US] 32 + Accéder à ma page d'accueil

### ISSUE THREAD

**Issue by KilianL55** [KilianL55/E-Music#37]
## Données du User Story

• En tant que Enfant,Parent

•  Accéder à ma page d'accueil

• afin de naviguer facilement sur l'application

## Team sur le projet

Team member : @Xeltax 

## Tâches à effectuer :

- [x] Création de la page dashboard
- [x] Pouvoir accéder directement une fois que je suis connecté
- [x] Créer une navigation simple

## Critères d'acceptation :
- [x] Je peux naviguer facilement sur l'application
