### ISSUE TITLE
[US] US 3 + Supprimer son compte

### ISSUE THREAD

**Issue by Xeltax** [KilianL55/E-Music#4]
# Modèle de création d'User Story

<h3>Données du User Story</h3>

• En tant que membre(enfant, parent, prof)

•  Je peux supprimer mon compte

• Afin d'arrêter mes activités liées à l’école de musique

## Team sur le projet

Team member : @KilianL55 

## Tâches à effectuer :

- [ ] Création d'un boutton
- [ ] Trouver l'utilisateur en base de données
- [ ] Supprimer cette utilisateur

## Critères d'acceptation :

- [ ] Je peux plus me connecter avec mes identifiants
