### ISSUE TITLE
[US] US 4 + Modifier ses informations personnelles

### ISSUE THREAD

**Issue by Xeltax** [KilianL55/E-Music#6]
# Modèle de création d'User Story

<h3>Données du User Story</h3>

• En tant qu’enfant ou parent

•  Je peux modifier mes informations personnels

• Afin de mettre à jour mes informations (adresse, numéro etc.)

## Team sur le projet

Team member : @KilianL55 

## Tâches à effectuer :

- [x] Création du formulaire
- [x] Récupérer les informations utilisateurs connectés
- [x] Mises à jour en base de données

## Critères d'acceptation :
- [x] Je peux mettre à jour mes données depuis l'application
